<?php
/**	op-layout-model:/template/lorem_ipsum.phtml
 *
 * @created     2026-01-29
 * @license     Apache-2.0
 * @package     op-layout-model
 * @copyright   Tomoaki Nagahara
 */

/**	Declare strict type
 *
 */
declare(strict_types=1);

/**	Namespace
 *
 */
namespace OP\LAYOUT\MODEL;

?>
<section>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
		Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
</section>
<section>
	<p>
		[32] Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo.
		Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem.
		Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
		Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?
	</p>
	<p>
		[33] At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga.
		Et harum quidem rerum facilis est et expedita distinctio.
		Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.
		Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae.
		Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
	</p>
</section>
<section>
	<p>
		[32]しかし私は、喜びを非難して苦痛を賞賛するという誤ったこの考えがすべてどのようにして誕生したかをあなたに説明しなければならないから、私はあなたにその体系を完璧に説明し、真実を求める偉大な探究家、人間の喜びを築く建築家の実践的な教えを詳しく説明しよう。
		だれも喜びそのものを、それが喜びであるという理由で拒んだり、嫌ったり、避けたりはしない。
		しかし、どのようにして喜びを理性的に追求するかを知らない人たちは非常に苦痛な結末に直面する。
		同様に、苦痛そのものを、それが苦痛であるという理由で愛したり、探したり、手に入れることを望んだりする者もいない。
		しかし、ときには苦労や苦痛がその人に大いなる喜びをいくらかもたらす状況がおこることがある。
		些末な例を挙げると、私たちのうちのだれが、そこから何か有益なものを得られないのに、骨の折れる肉体運動を引き受けるだろうか？しかしだれに、いらだたしい結末のない喜びを享受することを選ぶ人や、その結果としての喜びを生み出さないような痛みを避ける人にある、落ち度を見つける権利はあるのだろうか？
	</p>
	<p>
		[33]一方、わたしたちは正当な憤りをもって批判する。
		そして、今の喜びの魅力にだまされてあまりにもやる気を失い、欲望によってあまりにも盲目的になってしまうことで、その後に起こるべき苦痛や困難を予想できなくなってしまう人たちを嫌う；そして、同等の非難は意志の弱さによって自身の務めに失敗する人たちにも当てはまる。
		これは苦労から苦痛へと縮小することと等しい。
		これらの場合は完全に単純で、見分けるのはたやすい。
		自由なときにおいて、選択の力に制約がなく、いちばん好きなものを選ぶのに一切の妨げがないとき、あらゆる喜びが受け入れられ、あらゆる苦痛が避けられる。
		しかし、ある特定の状況において務めや義務により、しばしば喜びを拒み、いらだたしいことを受け入れなければならないことが起こる。
		賢い人間はそれゆえ常に、この選択の原則によってこれらの問題を制する：賢い人間は他のより大きな喜びを確実に手に入れるためならば喜びを拒み、あるいはよりひどいものを避けるために苦痛に耐える。
	</p>
</section>